version: '3.4'

services:

  shopprint_db:
    container_name: shopprint_db
    restart: always
    #command: [--auth]
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    #environment:
    # MONGO_INITDB_ROOT_USERNAME: shop
    # MONGO_INITDB_ROOT_PASSWORD: shopPrint@123
    # AUTH_MECHANISM: SCRAM-SHA-256


  #shopprint_api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "8001:80"
  #  depends_on:
  #    - shopprint_db